### ISSUE TITLE
Download Model Weights

### ISSUE THREAD

**Issue by Vujas-Eteph** [thanosDelatolas/eva-vos#1]
Hi there!👋 

First off, Great work!
I would like to use EVA-VOS for my research; however, I'm unable to download the model's weights... Do you have another link? As the one provided seems to be non-functional... https://github.com/thanosDelatolas/eva-vos/blob/34aebffb293174278ac6b0ed5d22847ee2fc813f/download_weights.py#L7-L8

Cheers!

**Comment by thanosDelatolas** [comment]
Hello, thank you for you kind words!😃
I have updated the link in the script. If anything else occurs, I am happy to help!

**Comment by Vujas-Eteph** [comment]
Great! Thanks for the quick response and the new links 🤗
